language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - TRANSPORT=jackrabbit
  - TRANSPORT=doctrine_dbal

before_script:
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit = 1024M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - cp app/config/phpcr_${TRANSPORT}.yml.dist app/config/phpcr.yml
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - ./app/tests/travis_${TRANSPORT}.sh
  - app/console doctrine:phpcr:workspace:create sandbox_test -e=test
  - app/console doctrine:phpcr:repository:init -e=test

script: phpunit -c app

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
